<?xml version="1.0" encoding="UTF-8"?>
<!-- @generated mapFile="xslt/ReqMap.map" md5sum="1422cbc8952d7d1a95810f62a5c2e962" version="8.0.200" -->
<!--
*****************************************************************************
*   This file has been generated by the IBM XML Mapping Editor.
*
*   Mapping file:		ReqMap.map
*   Map declaration(s):	ReqMap
*   Input file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FLoginModule%252FLoginModuleInterface%257DloginUserRequestMsg/xpath%3D%252F/smo.xsd
*   Output file(s):		smo://smo/name%3Dwsdl-primary/message%3D%257Bhttp%253A%252F%252FLoginModule%252FLoginComponentReference%257DloginRequestMsg/xpath%3D%252F/smo.xsd
*
*   Note: Do not modify the contents of this file as it is overwritten
*         each time the mapping model is updated.
*****************************************************************************
-->
<xsl:stylesheet
    xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:xalan="http://xml.apache.org/xslt"
    xmlns:str="http://exslt.org/strings"
    xmlns:set="http://exslt.org/sets"
    xmlns:math="http://exslt.org/math"
    xmlns:exsl="http://exslt.org/common"
    xmlns:date="http://exslt.org/dates-and-times"
    xmlns:in="http://LoginModule/LoginModuleInterface"
    xmlns:in2="wsdl.http://LoginModule/LoginModuleInterface"
    xmlns:io="http://www.w3.org/2003/05/soap-envelope"
    xmlns:io3="http://www.ibm.com/xmlns/prod/websphere/mq/sca/6.0.0"
    xmlns:io2="http://www.ibm.com/websphere/sibx/smo/v6.0.1"
    xmlns:out="wsdl.http://LoginModule/LoginComponentReference"
    xmlns:io4="http://schemas.xmlsoap.org/ws/2004/08/addressing"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:io5="http://www.ibm.com/xmlns/prod/websphere/http/sca/6.1.0"
    xmlns:out2="http://LoginModule/LoginComponentReference"
    xmlns:xs4xs="http://www.w3.org/2001/XMLSchema"
    xmlns:io6="http://www.w3.org/2005/08/addressing"
    xmlns:map="http://LoginModule/xslt/ReqMap"
    xmlns:msl="http://www.ibm.com/xmlmap"
    exclude-result-prefixes="in in2 str set math exsl date map xalan msl"
    version="1.0">
  <xsl:output method="xml" encoding="UTF-8" indent="no"/>

  <!-- root wrapper template  -->
  <xsl:template match="/">
    <xsl:choose>
      <xsl:when test="msl:datamap">
        <msl:datamap>
          <xsl:element name="dataObject">
            <xsl:attribute name="xsi:type">
              <xsl:value-of select="'io2:ServiceMessageObject'"/>
            </xsl:attribute>
            <xsl:call-template name="map:ReqMap2">
              <xsl:with-param name="smo" select="msl:datamap/dataObject[1]"/>
            </xsl:call-template>
          </xsl:element>
        </msl:datamap>
      </xsl:when>
      <xsl:otherwise>
        <xsl:apply-templates select="io2:smo" mode="map:ReqMap"/>
      </xsl:otherwise>
    </xsl:choose>
  </xsl:template>

  <!-- This rule represents an element mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template match="io2:smo"  mode="map:ReqMap">
    <io2:smo>
      <body>
        <xsl:attribute name="xsi:type">
          <xsl:value-of select="'out:loginRequestMsg'"/>
        </xsl:attribute>
        <out2:login>
          <!-- a simple data mapping: "body/in:loginUser/loginUserName"(string) to "userName"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space(body/in:loginUser/loginUserName)">
              <xsl:element name="userName">
                <xsl:value-of select="body/in:loginUser/loginUserName"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <userName xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
          <!-- a simple data mapping: "body/in:loginUser/loginPassword"(string) to "password"(string) -->
          <xsl:choose>
            <xsl:when test="normalize-space(body/in:loginUser/loginPassword)">
              <xsl:element name="password">
                <xsl:value-of select="body/in:loginUser/loginPassword"/>
              </xsl:element>
            </xsl:when>
            <xsl:otherwise>
              <password xsi:nil="true"/>
            </xsl:otherwise>
          </xsl:choose>
        </out2:login>
      </body>
    </io2:smo>
  </xsl:template>

  <!-- This rule represents a type mapping: "io2:smo" to "io2:smo".  -->
  <xsl:template name="map:ReqMap2">
    <xsl:param name="smo"/>
    <body>
      <xsl:attribute name="xsi:type">
        <xsl:value-of select="'out:loginRequestMsg'"/>
      </xsl:attribute>
      <out2:login>
        <!-- a simple data mapping: "$smo/body/in:loginUser/loginUserName"(string) to "userName"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space($smo/body/in:loginUser/loginUserName)">
            <xsl:element name="userName">
              <xsl:value-of select="$smo/body/in:loginUser/loginUserName"/>
            </xsl:element>
          </xsl:when>
          <xsl:otherwise>
            <userName xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
        <!-- a simple data mapping: "$smo/body/in:loginUser/loginPassword"(string) to "password"(string) -->
        <xsl:choose>
          <xsl:when test="normalize-space($smo/body/in:loginUser/loginPassword)">
            <xsl:element name="password">
              <xsl:value-of select="$smo/body/in:loginUser/loginPassword"/>
            </xsl:element>
          </xsl:when>
          <xsl:otherwise>
            <password xsi:nil="true"/>
          </xsl:otherwise>
        </xsl:choose>
      </out2:login>
    </body>
  </xsl:template>

  <!-- *****************    Utility Templates    ******************  -->
  <!-- copy the namespace declarations from the source to the target -->
  <xsl:template name="copyNamespaceDeclarations">
    <xsl:param name="root"/>
    <xsl:for-each select="$root/namespace::*[not(name() = '')]">
      <xsl:copy/>
    </xsl:for-each>
  </xsl:template>
</xsl:stylesheet>
